name: Deploy
on:
  push:
    branches:
      - main
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Switch to v4
      run: cd v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
    - name: Build
      run: |
        yarn
        yarn build
    - name: Deploy Dev
      if: github.ref == 'refs/heads/dev'
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: 198.187.29.221
        ssh-port: 21098
        remote-user: rarakiqz
        private-ssh-key: ${{ secrets.SSH_KEY }}
        source-path: ./dist/
        destination-path: ~/dev.raray.com/
